Repository yeoruti-study/front-end, pull requests merged in 2023-03, with the labels that each got.

#28 [여럿이-27] react-query 재사용 모듈 구현 및 스터디룸 api 연결
  package.json
  src/App.jsx
  src/api/common/RequestCore.ts
  src/api/roomUser/Resource.ts
  src/api/roomUser/index.ts
  src/api/roomUser/roomUserApiClient.ts
  src/api/roomUser/roomUserReq.ts
  src/api/roomUser/types/roomUserAPI.ts
  src/api/roomUser/types/roomUserType.ts
  src/api/studyRoom/Resource.ts
  src/api/studyRoom/index.ts
  src/api/studyRoom/studyRoomApiClient.ts
  src/api/studyRoom/studyRoomReq.ts
  src/api/studyRoom/studyRoomUriSelector.ts
  src/containers/StudyRoom/StudyHome.tsx
  src/hooks/react_query_hooks/useResource.ts
  src/hooks/react_query_hooks/useRoomUser.ts
  src/hooks/react_query_hooks/useStudyRoom.ts
  src/index.tsx
  src/utils/uriSelector.ts
  yarn.lock
Labels: ✨ feature

#29 [여럿이-24] 캘린더 기능 구현
  package-lock.json
  package.json
  src/App.jsx
  src/atoms/goal.ts
  src/common/Modal.tsx
  src/components/Calendar/CalendarModal.tsx
  src/components/Calendar/FullCalendar.tsx
  src/components/Calendar/style.css
  src/hooks/useCalendar.jsx
  yarn.lock
Labels: 🎨 style, ✨ feature

#32 [여럿이-31] 리액트 쿼리 hook 공통 모듈 fix
  src/api/common/RequestCore.ts
  src/components/StudyRoom/StudyUserList.tsx
  src/containers/StudyRoom/StudyRoomDetail.tsx
  src/hooks/react_query_hooks/useResource.ts
  src/hooks/react_query_hooks/useRoomUser.ts
  yarn.lock
Labels: 🐛 bug, ✨ feature

#34 [여럿이-33] 소셜 로그인 api 연동
  .gitignore
  src/App.jsx
  src/api/socialLogin/Resource.ts
  src/api/socialLogin/index.ts
  src/api/socialLogin/socialLoginApiClient.ts
  src/api/socialLogin/socialLoginReq.ts
  src/api/socialLogin/types/socialLoginAPI.ts
  src/components/Login/SocialLogin.jsx
  src/containers/OAuthContainer.tsx
  src/hooks/react_query_hooks/useSocialLogin.ts
  src/utils/parseSocialCode.ts
Labels: ✨ feature

#36 [여럿이-35] 스터디룸 상세 페이지 api 연동 및 레이아웃 구현 #35
  src/App.jsx
  src/api/roomUser/Resource.ts
  src/api/roomUser/roomUserApiClient.ts
  src/api/roomUser/roomUserReq.ts
  src/api/studyCategory/Resource.ts
  src/api/studyCategory/index.ts
  src/api/studyCategory/studyCategoryApiClient.ts
  src/api/studyCategory/studyCategoryReq.ts
  src/api/studyCategory/types/studyCategoryAPI.ts
  src/api/studyRoom/studyRoomApiClient.ts
  src/api/userStudySubject/Resource.ts
  src/api/userStudySubject/index.ts
  src/api/userStudySubject/types/userStudySubjectAPI.ts
  src/api/userStudySubject/types/userStudySubjectType.ts
  src/api/userStudySubject/userStudySubjectApiClient.ts
  src/api/userStudySubject/userStudySubjectReq.ts
  src/atoms/categoryAdd.ts
  src/atoms/myStudyRoom.ts
  src/atoms/studyRoom.ts
  src/components/StudyRoom/CategoryAddPopup/CategoryAddPopup.tsx
  src/components/StudyRoom/StudyRoomAdd/StudyRoomAdd.tsx
  src/components/StudyRoom/StudyRoomAdd/StudyRoomCategory.tsx
  src/components/StudyRoom/StudyRoomAdd/StudyRoomFormItem.tsx
  src/components/StudyRoom/StudyRoomLayout.tsx
  src/components/StudyRoom/StudyRoomList.tsx
  src/containers/LoginContainer.jsx
  src/containers/OAuthContainer.tsx
  src/containers/StudyRoom/MyStudyRoomContainer.tsx
  src/containers/StudyRoom/StudyRoomContainer.tsx
  src/hooks/react_query_hooks/useRoomUser.ts
  src/hooks/react_query_hooks/useStudyCategory.ts
  src/index.tsx
  src/pages/MyStudyRoom.tsx
  src/pages/StudyRoom.tsx
  src/style/index.css
  src/utils/getFieldError.ts
Labels: ✨ feature

#37 [여럿이-35_2] 스터디룸 상세 페이지 api 연동 및 레이아웃 구현 #35
  src/App.jsx
  src/api/common/axiosClient.ts
  src/api/roomUser/types/roomUserAPI.ts
  src/api/roomUser/types/roomUserType.ts
  src/api/studyRoom/Resource.ts
  src/api/studyRoom/types/studyRoomAPI.ts
  src/api/studyRoom/types/studyRoomType.ts
  src/api/user/Resource.ts
  src/api/user/index.ts
  src/api/user/types/userAPI.ts
  src/api/user/userReq.ts
  src/atoms/curStudyRoom.ts
  src/atoms/myStudyRoom.ts
  src/atoms/userInfo.ts
  src/components/Navigation/Navigation.tsx
  src/components/Router/PrivateRoute.tsx
  src/components/Router/PublicRoute.tsx
  src/components/Router/types/Route.ts
  src/components/StudyRoom/StudyList.tsx
  src/components/StudyRoom/StudyRoomAdd/StudyRoomAdd.tsx
  src/components/StudyRoom/StudyRoomAdd/StudyRoomCategory.tsx
  src/components/StudyRoom/StudyRoomItem.tsx
  src/components/StudyRoom/StudyRoomLayout.tsx
  src/components/StudyRoom/StudyRoomList.tsx
  src/components/StudyRoom/StudyUserList.tsx
  src/containers/OAuthContainer.tsx
  src/containers/StudyRoom/MyStudyRoomContainer.tsx
  src/containers/StudyRoom/StudyHome.tsx
  src/containers/StudyRoom/StudyRoomContainer.tsx
  src/containers/SubjectContainer.tsx
  src/hooks/react_query_hooks/useRoomUser.ts
  src/hooks/react_query_hooks/useStudyRoom.ts
  src/hooks/react_query_hooks/useUser.ts
  src/index.tsx
  src/utils/getFieldError.ts
Labels: ✨ feature

#39 [여럿이-38] PR#37 머지 bug fix
  src/components/StudyRoom/StudyRoomAdd/StudyRoomCategory.tsx
Labels: 🐛 bug

#42 [여럿이-41] 스터디룸 비밀번호 기능 구현
  src/components/StudyRoom/CategoryAddPopup/CategoryAddPopup.tsx
  src/components/StudyRoom/StudyRoomAdd/StudyRoomAdd.tsx
  src/components/StudyRoom/StudyRoomAdd/StudyRoomCategory.tsx
  src/components/StudyRoom/StudyRoomAdd/StudyRoomFormItem.tsx
  src/hooks/react_query_hooks/useStudyRoom.ts
  src/utils/getFieldError.ts
Labels: ✨ feature

#44 [여럿이-43] 스터디룸 카테고리 필터 기능 구현
  src/atoms/studyRoomFilter.ts
  src/components/StudyRoom/StudyModal/StudyModal.tsx
  src/components/StudyRoom/StudyRoomFilter/StudyRoomFilter.tsx
  src/components/StudyRoom/StudyRoomItem.tsx
  src/components/StudyRoom/StudyRoomList.tsx
  src/components/StudyRoom/StudyRoomSearch/StudyRoomSearch.tsx
  src/containers/StudyRoom/MyStudyRoomContainer.tsx
  src/containers/StudyRoom/StudyRoomContainer.tsx
Labels: ✨ feature

#50 [여럿이-49] 리팩토링 및 UI 업데이트
  src/api/temporary/index.ts
  src/api/temporary/logoutApiClient.ts
  src/assets/logo_black.png
  src/assets/logo_no_background.png
  src/atoms/curStudyRoom.ts
  src/atoms/studyPwPopup.ts
  src/components/Navigation/Navigation.tsx
  src/components/StudyRoom/CategoryAddPopup/CategoryAddPopup.tsx
  src/components/StudyRoom/StudyPasswordPopup/PasswordPopup.tsx
  src/components/StudyRoom/StudyRoomAdd/StudyRoomCategory.tsx
  src/components/StudyRoom/StudyRoomItem.tsx
  src/components/SubjectAddDelete/SubjectAddDelete.tsx
  src/containers/StudyRoom/MyStudyRoomContainer.tsx
  src/hooks/react_query_hooks/useStudyCategory.ts
  src/hooks/react_query_hooks/useStudyRoom.ts
Labels: 🎨 style, ✨ feature, ♻️ refactor

#52 [여럿이-51] svg 속성 warning 해결 및 스터디룸 api 업데이트
  src/api/studyRoom/types/studyRoomType.ts
  src/atoms/curStudyRoom.ts
  src/components/StudyRoom/StudyRoomAdd/StudyRoomFormItem.tsx
  src/components/StudyRoom/StudyRoomFilter/StudyRoomFilter.tsx
  src/components/StudyRoom/StudyRoomItem.tsx
  src/components/StudyRoom/StudyRoomLayout.tsx
  src/components/StudyRoom/StudyRoomSearch/StudyRoomSearch.tsx
  src/containers/StudyRoom/MyStudyRoomContainer.tsx
  src/containers/StudyRoom/StudyRoomContainer.tsx
  src/hooks/react_query_hooks/useStudyCategory.ts
  src/hooks/react_query_hooks/useStudyRoom.ts
  src/style/GlobalStyles.jsx
Labels: ✨ feature, ♻️ refactor
